# Generated by Django 6.0.7 on 2026-07-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_coins',
            field=models.PositiveIntegerField(default=0, help_text='Loyalty coins earned from orders'),
        ),
    ]
