# Generated by Django 6.0.7 on 2026-07-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_loyalty_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text="User's date of birth for birthday vouchers", null=True),
        ),
    ]
