# Generated by Django 6.0.7 on 2026-07-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_ru',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='category',
            name='name_uz',
            field=models.CharField(default='Category', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_uz',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uz',
            field=models.CharField(default='Product', max_length=255),
            preserve_default=False,
        ),
    ]
